"""
Config loader for Bambu AMS payloads.
Loads and caches all configuration files from the config directory.
"""

import json
import re
from pathlib import Path
from typing import Any, Dict, Optional, List, Tuple

# Files in config/printers/ that describe the set of printers, not one printer.
_PRINTER_META_FILES = {"index.json", "names.json"}


class AmbiguousPrinterNameError(ValueError):
    """A printer name is shared by more than one model id.

    Subclasses ValueError so existing `except ValueError` handling around
    printer lookups keeps working.
    """

    def __init__(self, name: str, model_ids: List[str]):
        self.name = name
        self.model_ids = list(model_ids)
        super().__init__(
            f"Printer name '{name}' is shared by more than one model: "
            f"{', '.join(self.model_ids)}. Pass one of those model ids instead."
        )


class ConfigLoader:
    """Loads and caches configuration files for payload generation.

    Instances are cached per config directory: constructing one for a directory
    already loaded returns the existing instance instead of re-reading a few
    hundred JSON files. The cache is keyed by resolved path, so a second
    directory gets its own instance rather than silently reusing the first.
    """

    _instances: Dict[Path, "ConfigLoader"] = {}

    @staticmethod
    def _resolve_config_dir(config_dir: Optional[Path]) -> Path:
        """Normalize a config dir argument into the key used to cache it."""
        if config_dir is None:
            config_dir = Path(__file__).parent / "config"
        return Path(config_dir).expanduser().resolve()

    def __new__(cls, config_dir: Optional[Path] = None):
        key = cls._resolve_config_dir(config_dir)
        instance = cls._instances.get(key)
        if instance is None:
            instance = super().__new__(cls)
            instance._initialized = False
            cls._instances[key] = instance
        return instance

    @classmethod
    def clear_cache(cls) -> None:
        """Drop all cached instances, so the next load re-reads from disk.

        Needed after regenerating the config files in a long-running process,
        and to keep tests that use different config directories isolated.
        """
        cls._instances.clear()

    def __init__(self, config_dir: Optional[Path] = None):
        if self._initialized:
            return

        self.config_dir = self._resolve_config_dir(config_dir)
        self._printers: Dict[str, Dict] = {}
        self._commands: Dict[str, Dict] = {}
        self._enums: Dict[str, Dict] = {}
        self._virtual_ids: Dict[str, Any] = {}
        self._filament_presets: Dict[str, Dict] = {}
        self._feature_flags: Dict[str, Any] = {}
        self._ams_response_format: Dict[str, Any] = {}
        self._printer_index: List[Dict] = []
        self._command_index: List[Dict] = []
        self._filament_index: List[Dict] = []
        
        self._load_all()
        self._initialized = True
    
    def _load_all(self):
        """Load all configuration files."""
        # Printers
        printers_dir = self.config_dir / "printers"
        for f in printers_dir.glob("*.json"):
            if f.name not in _PRINTER_META_FILES:
                with open(f) as fp:
                    self._printers[f.stem] = json.load(fp)

        # Load index
        with open(printers_dir / "index.json") as fp:
            self._printer_index = json.load(fp)

        # Name -> model id map, generated by bambu-mqtt-extractor. Display names
        # are not unique in Bambu Studio, so the extractor resolves them once and
        # records any it cannot (see _resolve_model_id).
        names_file = printers_dir / "names.json"
        if names_file.exists():
            with open(names_file) as fp:
                names = json.load(fp)
            self._printer_names = names.get("names", {})
            self._ambiguous_printer_names = names.get("ambiguous", {})
        else:
            self._printer_names, self._ambiguous_printer_names = \
                self._build_name_to_model_id_map()

        # Model ids are matched case-insensitively; keep the canonical spelling.
        self._model_id_lookup = {mid.lower(): mid for mid in self._printers}

        # Commands
        commands_dir = self.config_dir / "commands"
        for f in commands_dir.glob("*.json"):
            if f.name != "index.json":
                with open(f) as fp:
                    self._commands[f.stem] = json.load(fp)
        
        # Enums
        enums_dir = self.config_dir / "enums"
        for f in enums_dir.glob("*.json"):
            if f.name != "index.json":
                with open(f) as fp:
                    self._enums[f.stem] = json.load(fp)
        
        # Virtual IDs
        with open(self.config_dir / "virtual_ids.json") as fp:
            self._virtual_ids = json.load(fp)
        
        # Filament presets
        filament_dir = self.config_dir / "filament_presets"
        for f in filament_dir.glob("*.json"):
            if f.name != "index.json":
                with open(f) as fp:
                    self._filament_presets[f.stem] = json.load(fp)
        
        with open(filament_dir / "index.json") as fp:
            self._filament_index = json.load(fp)
        
        # Feature flags
        with open(self.config_dir / "feature_flags.json") as fp:
            self._feature_flags = json.load(fp)

        # AMS / external-spool response contract. Model-independent: Bambu
        # Studio uses one parser for every printer and detects the shape at
        # runtime, so this is a single file rather than a per-printer guess.
        ams_format_file = self.config_dir / "ams_response_format.json"
        if ams_format_file.exists():
            with open(ams_format_file) as fp:
                self._ams_response_format = json.load(fp)
    
    # --- Accessor methods ---
    
    def get_printer(self, model_id: str) -> Optional[Dict]:
        """Get printer config by model ID (e.g., 'BL-P001', 'C11').

        Accepts a printer name ('X1 Carbon') too, and matches either form
        case-insensitively. Returns None if unknown; raises
        AmbiguousPrinterNameError for a name shared by several models.
        """
        resolved = self._resolve_model_id(model_id)
        return self._printers.get(resolved) if resolved else None
    
    def get_printer_index(self) -> List[Dict]:
        """Get list of all available printers."""
        return self._printer_index
    
    def get_command(self, command_name: str) -> Optional[Dict]:
        """Get command spec by name."""
        return self._commands.get(command_name)
    
    def get_enum(self, enum_name: str) -> Optional[Dict]:
        """Get enum values by name."""
        return self._enums.get(enum_name)
    
    def get_virtual_ids(self) -> Dict[str, Any]:
        """Get virtual ID constants."""
        return self._virtual_ids
    
    def get_filament_preset(self, filament_id: str) -> Optional[Dict]:
        """Get filament preset by ID (e.g., 'GFU01')."""
        return self._filament_presets.get(filament_id)
    
    def get_filament_index(self) -> List[Dict]:
        """Get list of all filament presets."""
        return self._filament_index
    
    def get_feature_flags(self) -> Dict[str, Any]:
        """Get feature flags matrix."""
        return self._feature_flags

    def get_ams_response_format(self) -> Dict[str, Any]:
        """
        Get the AMS / external-spool push_status response contract.

        This describes where AMS slots and the external spool live in a
        push_status payload, and how their ids map onto command fields. It is
        the same for every printer model and firmware.
        """
        return self._ams_response_format
    
    def supports_feature(self, model_id: str, firmware_version: str, feature: str) -> bool:
        """Check if a printer model at a firmware version supports a feature."""
        flags = self._feature_flags.get("printer_support", {})
        model_flags = flags.get(self._resolve_model_id(model_id) or model_id, {})
        version_flags = model_flags.get(firmware_version, {})
        return version_flags.get(feature, False)
    
    def get_firmware_versions(self, model_id: str) -> List[str]:
        """Get sorted list of firmware versions for a printer model."""
        printer = self.get_printer(model_id)
        if not printer:
            return []
        return sorted(printer.get("firmware_versions", {}).keys(), 
                      key=lambda v: tuple(map(int, v.split("."))))

    def get_closest_firmware_version(self, model_id: str, target_version: str) -> Optional[str]:
        """
        Find the closest matching firmware version for a printer model.
        
        Returns the highest available version that is <= target_version.
        If target_version is older than all available versions, returns the oldest.
        If target_version exactly matches an available version, returns it.
        
        Args:
            model_id: Printer model ID (e.g., "N1", "N7")
            target_version: Target firmware version string (e.g., "01.05.00.00")
            
        Returns:
            Closest matching firmware version or None if no versions available
        """
        versions = self.get_firmware_versions(model_id)
        if not versions:
            return None
            
        def version_tuple(v: str) -> tuple:
            return tuple(map(int, v.split(".")))
        
        target_tuple = version_tuple(target_version)
        
        # Find versions <= target
        candidates = [v for v in versions if version_tuple(v) <= target_tuple]
        
        if candidates:
            # Return highest candidate (closest but not exceeding target)
            return max(candidates, key=version_tuple)
        else:
            # Target is older than all available - return oldest
            return min(versions, key=version_tuple)

    def _normalize_printer_name(self, name: str) -> str:
        """Normalize printer name for matching: lowercase, collapse whitespace."""
        return re.sub(r'\s+', ' ', name.strip().lower())
    
    def _build_name_to_model_id_map(self) -> Tuple[Dict[str, str], Dict[str, List[str]]]:
        """Build name -> model id maps from the printer configs.

        Fallback for config directories predating printers/names.json. Mirrors
        what the extractor generates, including collision handling: a name
        claimed by several models resolves to none of them.
        """
        claims: Dict[str, set] = {}
        for model_id, printer in self._printers.items():
            display_name = printer.get("display_name", "")
            if not display_name:
                continue
            # Users say "X1 Carbon", not "Bambu Lab X1 Carbon".
            if display_name.lower().startswith("bambu lab "):
                display_name = display_name[len("bambu lab "):]
            claims.setdefault(self._normalize_printer_name(display_name), set()).add(model_id)

        names = {n: sorted(ids)[0] for n, ids in claims.items() if len(ids) == 1}
        ambiguous = {n: sorted(ids) for n, ids in claims.items() if len(ids) > 1}
        return names, ambiguous

    def _resolve_model_id(self, identifier: str) -> Optional[str]:
        """Resolve a model ID or printer name to a model ID.

        Both forms are case-insensitive, and surrounding/repeated whitespace is
        ignored.

        Args:
            identifier: Either a model ID (e.g., "BL-P001") or printer name
                       (e.g., "X1 Carbon", "P1P", "A1 mini")

        Returns:
            Model ID if found, None otherwise

        Raises:
            AmbiguousPrinterNameError: the name belongs to several models, so
                only a model id can say which one is meant.
        """
        normalized = self._normalize_printer_name(identifier)

        # A model id, in any casing.
        model_id = self._model_id_lookup.get(normalized)
        if model_id:
            return model_id

        # A printer name.
        model_id = self._printer_names.get(normalized)
        if model_id:
            return model_id

        if normalized in self._ambiguous_printer_names:
            raise AmbiguousPrinterNameError(
                identifier.strip(), self._ambiguous_printer_names[normalized]
            )

        return None

    def get_payload_builder(self, model_id: str, firmware_version: str):
        """Get a PayloadBuilder for a specific printer and firmware version.
        
        Args:
            model_id: Either a model ID (e.g., "BL-P001") or printer name 
                      (e.g., "X1 Carbon", "P1P", "A1")
            firmware_version: Firmware version string (e.g., "01.05.06.06")
                              If exact version not found, closest earlier version is used.
        """
        resolved_model_id = self._resolve_model_id(model_id)
        if not resolved_model_id:
            raise ValueError(f"Unknown printer model: {model_id}")
        
        # Find closest matching firmware version
        closest_version = self.get_closest_firmware_version(resolved_model_id, firmware_version)
        if not closest_version:
            raise ValueError(f"No firmware versions available for model: {resolved_model_id}")
        if closest_version != firmware_version:
            # Expected, not an error: Bambu Studio only defines a firmware entry
            # where behaviour changes, so most versions inherit an earlier one.
            print(f"[bambu-mqtt-generator] No config changes recorded for "
                  f"{resolved_model_id} firmware '{firmware_version}'; using the "
                  f"nearest earlier entry '{closest_version}'")
        
        from .payload_builder import PayloadBuilder
        return PayloadBuilder(self, resolved_model_id, closest_version)


# Convenience function
def load_config(config_dir: Optional[Path] = None) -> ConfigLoader:
    """Get the ConfigLoader for a config directory, loading it once and caching it.

    Omit config_dir for the config bundled with the library. Call
    ConfigLoader.clear_cache() to force a reload from disk.
    """
    return ConfigLoader(config_dir)


def get_payload_builder(model_id: str, firmware_version: str, config_dir: Optional[Path] = None):
    """Get a PayloadBuilder for a specific printer and firmware version."""
    config = ConfigLoader(config_dir)
    return config.get_payload_builder(model_id, firmware_version)